<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_58a278623bb5e',
	'title' => 'Author',
	'fields' => array (
		array (
			'key' => 'field_58a278671fe82',
			'label' => 'Twitter',
			'name' => 'acf_twitter',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'author',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_589e875814595',
	'title' => 'Explainer',
	'fields' => array (
		array (
			'key' => 'field_589e877c9a618',
			'label' => 'Subtítulo',
			'name' => 'acf_subtitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_589e87ce9a619',
			'label' => 'Temas',
			'name' => 'acf_topics',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => '',
			'collapsed' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_589e88199a61a',
					'label' => 'Título',
					'name' => 'acf_topic_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array (
					'key' => 'field_589e88329a61b',
					'label' => 'Contenido',
					'name' => 'acf_topic_content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'default_value' => '',
					'delay' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:x-plainers',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_58a8972dc27b6',
	'title' => 'Options Generales',
	'fields' => array (
		array (
			'key' => 'field_58a8974c80b77',
			'label' => 'Facebook',
			'name' => 'acf_options_facebook',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_58a8976d80b78',
			'label' => 'Twitter',
			'name' => 'acf_options_twitter',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_58a8977780b79',
			'label' => 'Youtube',
			'name' => 'acf_options_youtube',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_58acf131b590c',
			'label' => 'Aviso de privacidad',
			'name' => 'acf_privacy_url',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-general',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_58a21290da9b6',
	'title' => 'Page Section',
	'fields' => array (
		array (
			'key' => 'field_58a212a01938c',
			'label' => 'Destacados',
			'name' => 'acf_featured_news',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'post',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'elements' => array (
				0 => 'featured_image',
			),
			'min' => '',
			'max' => 4,
			'return_format' => 'object',
		),
		array (
			'key' => 'field_58a2130b1938d',
			'label' => 'Más Noticias',
			'name' => 'acf_more_news',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'post',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'elements' => array (
				0 => 'featured_image',
			),
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
		array (
			'key' => 'field_58a8ab0f95e43',
			'label' => 'Cargar más de',
			'name' => 'acf_load_more_terms',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'multi_select',
			'allow_null' => 0,
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'object',
			'multiple' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-section.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_589e7de8d652b',
	'title' => 'Post',
	'fields' => array (
		array (
			'key' => 'field_58a275a75b7e4',
			'label' => 'Autor',
			'name' => 'acf_author',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'author',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'elements' => array (
				0 => 'featured_image',
			),
			'min' => '',
			'max' => 1,
			'return_format' => 'object',
		),
		array (
			'key' => 'field_589e7e00a5c25',
			'label' => 'Entradas Relacionadas',
			'name' => 'acf_related_posts',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'post',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'elements' => array (
				0 => 'featured_image',
			),
			'min' => '',
			'max' => 3,
			'return_format' => 'object',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_58ac8b43c9755',
	'title' => 'Taxonomy',
	'fields' => array (
		array (
			'key' => 'field_58ac8b5f3e204',
			'label' => 'Videos',
			'name' => 'acf_is_video',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5887d2e748694',
	'title' => 'Template Home',
	'fields' => array (
		array (
			'key' => 'field_58a1c290498b8',
			'label' => 'Noticia destacada',
			'name' => 'featured_news_item',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => 1,
			'button_label' => 'Add Row',
			'layouts' => array (
				array (
					'key' => '58a1c2a353f0f',
					'name' => 'post',
					'label' => 'Entrada',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_58a1c2b5498b9',
							'label' => 'Post',
							'name' => 'featured_news_item_post',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '58a1c2d1498ba',
					'name' => 'custom',
					'label' => 'Personalizado',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_58a1c2db498bb',
							'label' => 'Imagen',
							'name' => 'featured_news_item_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_58a1c2f3498bc',
							'label' => 'Enlace',
							'name' => 'featured_news_item_link',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_58a1c302498bd',
							'label' => 'Título',
							'name' => 'featured_news_item_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array (
							'key' => 'field_58a1c30a498be',
							'label' => 'Abrir en una nueva ventana',
							'name' => 'featured_news_item_new_window',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 0,
							'message' => '',
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
		array (
			'key' => 'field_58acd757184ea',
			'label' => 'Noticias destacadas',
			'name' => 'acf_featured_news',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'elements' => array (
				0 => 'featured_image',
			),
			'min' => '',
			'max' => 3,
			'return_format' => 'object',
		),
		array (
			'key' => 'field_58a1d3c612cde',
			'label' => 'Sección 1',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_58a1d40313e22',
			'label' => 'Bloques',
			'name' => 'section_1_blocks',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 0,
			'max' => 3,
			'layout' => 'block',
			'button_label' => '',
			'collapsed' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_58a1d42313e23',
					'label' => 'Bloque',
					'name' => 'block_item',
					'type' => 'flexible_content',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'min' => '',
					'max' => 1,
					'button_label' => 'Add Row',
					'layouts' => array (
						array (
							'key' => '58a1d6175a2a0',
							'name' => 'category',
							'label' => 'Categoría',
							'display' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_58a1d628003dd',
									'label' => 'Categoría',
									'name' => 'block_item_cat',
									'type' => 'taxonomy',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'taxonomy' => 'category',
									'field_type' => 'select',
									'allow_null' => 0,
									'add_term' => 1,
									'save_terms' => 0,
									'load_terms' => 0,
									'return_format' => 'object',
									'multiple' => 0,
								),
							),
							'min' => '',
							'max' => '',
						),
						array (
							'key' => '58a1d654003de',
							'name' => 'custom',
							'label' => 'Personalizado',
							'display' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_58a1d65e003df',
									'label' => 'Título del bloque',
									'name' => 'block_item_title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array (
									'key' => 'field_58a1d673003e0',
									'label' => 'Posts',
									'name' => 'block_item_posts',
									'type' => 'relationship',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => array (
										0 => 'post',
									),
									'taxonomy' => array (
									),
									'filters' => array (
										0 => 'search',
									),
									'elements' => array (
										0 => 'featured_image',
									),
									'min' => '',
									'max' => 4,
									'return_format' => 'object',
								),
							),
							'min' => '',
							'max' => '',
						),
					),
				),
			),
		),
		array (
			'key' => 'field_5887d2f157d1e',
			'label' => 'Categorías destacadas',
			'name' => 'featured_categories',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'multi_select',
			'multiple' => 0,
			'allow_null' => 1,
			'return_format' => 'object',
			'add_term' => 1,
			'load_terms' => 0,
			'save_terms' => 0,
		),
		array (
			'key' => 'field_5887e411dd4c3',
			'label' => 'Categoría central',
			'name' => 'central_category',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'select',
			'multiple' => 0,
			'allow_null' => 1,
			'return_format' => 'object',
			'add_term' => 1,
			'load_terms' => 0,
			'save_terms' => 0,
		),
		array (
			'key' => 'field_588803227dc50',
			'label' => 'Categoría Explainers',
			'name' => 'explainers_category',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'select',
			'multiple' => 0,
			'allow_null' => 1,
			'return_format' => 'object',
			'add_term' => 1,
			'load_terms' => 0,
			'save_terms' => 0,
		),
		array (
			'key' => 'field_58a1e46d43f51',
			'label' => 'Sección 2 (Videos)',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_58a1e48d43f52',
			'label' => 'Bloque',
			'name' => 'section_2_block',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => 1,
			'button_label' => 'Add Row',
			'layouts' => array (
				array (
					'key' => '58a1e4d30938e',
					'name' => 'category',
					'label' => 'Caregoría',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_58a1e4e343f53',
							'label' => 'Cartegoría',
							'name' => 'block_item_cat',
							'type' => 'taxonomy',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'category',
							'field_type' => 'select',
							'allow_null' => 0,
							'add_term' => 1,
							'save_terms' => 0,
							'load_terms' => 0,
							'return_format' => 'object',
							'multiple' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '58a1e53043f54',
					'name' => 'custom',
					'label' => 'Personalizado',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_58a1e53c43f55',
							'label' => 'Título',
							'name' => 'block_item_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array (
							'key' => 'field_58a1e55543f56',
							'label' => 'Posts',
							'name' => 'block_item_posts',
							'type' => 'relationship',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
								0 => 'post',
							),
							'taxonomy' => array (
							),
							'filters' => array (
								0 => 'search',
							),
							'elements' => array (
								0 => 'featured_image',
							),
							'min' => '',
							'max' => 3,
							'return_format' => 'object',
						),
						array (
							'key' => 'field_58a1eb18f700a',
							'label' => 'Enlace ver más',
							'name' => 'block_item_link',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_58a1eb37f700b',
							'label' => 'Abrir en una nueva ventana',
							'name' => 'block_item_new_window',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 0,
							'message' => '',
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
		array (
			'key' => 'field_58a1eec9c753e',
			'label' => 'Sección 3',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5887f343df914',
			'label' => 'Titulares',
			'name' => 'headlines',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'post',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'elements' => array (
				0 => 'featured_image',
			),
			'min' => '',
			'max' => 3,
			'return_format' => 'object',
		),
		array (
			'key' => 'field_58b8475354c1e',
			'label' => 'Enlace (Ver más)',
			'name' => 'section_3_more_link',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_58b8477154c1f',
			'label' => 'Etiqueta (Ver más)',
			'name' => 'section_3_more_caption',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_58a1f0bfe9e83',
			'label' => 'Sección 4 (Explainers)',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_58a1f0dfe9e84',
			'label' => 'Entradas',
			'name' => 'section_4_entries',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'post',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'elements' => array (
				0 => 'featured_image',
			),
			'min' => '',
			'max' => 3,
			'return_format' => 'object',
		),
		array (
			'key' => 'field_58a1f1ad20310',
			'label' => 'Enlace (Ver más)',
			'name' => 'section_4_more_link',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_58a1f1d120311',
			'label' => 'Etiqueta (Ver más)',
			'name' => 'section_4_more_caption',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_58a1f6239c38f',
			'label' => 'Sección 5',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_58a1f6359c390',
			'label' => 'Entradas',
			'name' => 'section_5_entries',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'post',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'elements' => array (
				0 => 'featured_image',
			),
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-home.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

endif;